import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";
import rohit from "../rohit/wp.jpg";
// import code from "../public/code.png";
// import design from "../public/design.png";
// import consulting from "../public/consulting.png";
// import Image from "next/image";
// import web1 from "../public/web1.png";
// import web2 from "../public/web2.png";
// import web3 from "../public/web3.png";
// import web4 from "../public/web4.png";
// import web5 from "../public/web5.png";
// import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Rohit Kanyal</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  World of Coding
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
             Recurtion
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              The Power of Algorithms
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Today I am Going to Explain what is Recution what it is used for any why should you learn it right now!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              
              <Image src={rohit} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Recution</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              It has used in every persons life in every part of life simply it ominvorsise present in day today life.
              <span className="text-teal-500"> Nature </span>
              consulted for <span className="text-teal-500">Animals </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Name it one or other way it will depeand on recurtion.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={rohit} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                  hello how are you doing
              </h3>
              <p className="py-2">
                To Know more you can help your self by going deep down in recurstion by your self.
              </p>
              <h4 className="py-4 text-teal-600">It used in Law</h4>
              <p className="text-gray-800 py-1">Development</p>
              <p className="text-gray-800 py-1">Animal</p>
              <p className="text-gray-800 py-1">Nature</p>
              <p className="text-gray-800 py-1">Universe</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={rohit} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Go Out and see it's magic
              </h3>
              <p className="py-2">
                Once you see it you will love to know about it all.
              </p>
              <h4 className="py-4 text-teal-600">Just be cursious</h4>
              <p className="text-gray-800 py-1">Just be cursious</p>
              <p className="text-gray-800 py-1">Just be cursious</p>
              <p className="text-gray-800 py-1">Just be cursious</p>
              <p className="text-gray-800 py-1">Just be cursious</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={rohit} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Just be cursious</h3>
              <p className="py-2">
              Just be cursious
              </p>
              <h4 className="py-4 text-teal-600">Just be cursiousn </h4>
              <p className="text-gray-800 py-1">Just be cursiousshop</p>
              <p className="text-gray-800 py-1">Just be cursioustrator</p>
              <p className="text-gray-800 py-1">Just be cursious</p>
              <p className="text-gray-800 py-1">Just be cursiousi</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Go out and find</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Just be cursious
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              Just be cursious
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Just be cursious
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                 src={rohit}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                 src={rohit}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                 src={rohit}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                 src={rohit}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                 src={rohit}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                 src={rohit}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
